### ISSUE TITLE
Versão 1.4.1 not working onLaunch app closed

### ISSUE THREAD

**Issue by moreirawebmaster** [mwaylabs/flutter-apns#52] opened 2021-03-23 18:32 UTC
I did the whole process and it works perfectly, onMessage, onResume.

onLaunch is not called when the app is closed, see my implementation:

import 'package:flutter_apns/apns.dart';

import '../utilities/notifications.dart';

class PushNotificationService extends GetxService {
  String token;
  bool isAction = false;

  Future<void> initNotification() async {
    print('PUSH - INICIALIZADO');
    final connector = createPushConnector()
   
    connector.configure(
      onMessage: (Map<String, dynamic> message) {
        print('PUSH - onMessage');
        String title, body, action;

        if (connector is ApnsPushConnector) {
          title = message['aps']['alert']['title'] ?? '';
          body = message['aps']['alert']['body'] ?? '';
          action = message['aps']['action'] ?? '';
        } else {
          title = message['data']['title'] ?? '';
          body = message['data']['body'] ?? '';
          action = message['data']['action'];
        }
          
        }
        return Future.value();
      },
      onBackgroundMessage: (Map<String, dynamic> message) async {
        print('PUSH - onBackgroundMessage');
        String action;
        if (connector is ApnsPushConnector) {
          action = message['aps']['action'] ?? '';
        } else {
          action = message['data']['action'] ?? '';
        }
      },
      onLaunch: (Map<String, dynamic> message) async {
        print('PUSH - onLaunch');
        String action;
        if (connector is ApnsPushConnector) {
          action = message['aps']['action'] ?? '';
        } else {
          action = message['data']['action'] ?? '';
        }
      },
      onResume: (Map<String, dynamic> message) async {
        print('PUSH - onResume');
        String action;
        if (connector is ApnsPushConnector) {
          action = message['aps']['action'] ?? '';
        } else {
          action = message['data']['action'] ?? '';
        }
          return Future.value();
      },
    );

    connector.token.addListener(() {
      try {
        token = connector.token.value;
        print('TOKEN: $token');
      } catch (e) {}
    });

    connector.requestNotificationPermissions();

    if (connector is ApnsPushConnector) {
      connector.shouldPresent = (Map<String, dynamic> message) {
        return Future.value(false);
      };
    }

    token = connector.token?.value;
  }
}

**Comment by szotp** [comment] 2021-03-24 07:11
Please check on latest prelease (1.5.0-dev.1). Note that this must be tested in release mode, otherwise app will just crash on start (known bug https://github.com/flutter/flutter/issues/67624#issuecomment-801971172).

**Comment by mrdc** [comment] 2021-03-24 11:30
> Please check on latest prelease (1.5.0-dev.1)

Hi, I'm testing this version right now. When app is in foreground `payload.data.entries.first.key` and `payload.data.entries.first.value` do work - I have access to the data, but when going from background to foreground with `onResume`, these fields are empty: in logs `actionIdentifier:com.apple.UNNotificationDefaultActionIdentifier` instead of real data.

BTW How can I access data in apns 1.5.0+ as in earlier versions: something like this: `message['aps']['alert']['body']`?

**Comment by szotp** [comment] 2021-03-24 11:35
> BTW How can I access data in apns 1.5.0+ as in earlier versions: something like this: message['aps']['alert']['body']?

That's not possible, because firebase_messaging on Android side has discarded Map<String, dynamic> in favor of RemoteMessage object. But you should be able to get body parameter with `payload.notification.body`

**Comment by szotp** [comment] 2021-03-24 11:36
I think I know what me the issue you reported, will check later today.

**Comment by mrdc** [comment] 2021-03-24 12:03
> That's not possible, because firebase_messaging on Android side has discarded Map<String, dynamic> in favor of RemoteMessage object. But you should be able to get body parameter with `payload.notification.body`

Thanks, it works. Also for subtitle, sound, badge etc via `payload.notification.apple`

I'm quite new to all this firebase stuff, so it's not clear - I'm using iOS, so should I switch to `flutter_apns_only`?

**Comment by szotp** [comment] 2021-03-24 12:06
For most use cases I recommend using flutter_apns. If you are not supporting Android, or want to have custom notification handling there, you can go with flutter_apns_only.

**Comment by szotp** [comment] 2021-03-24 12:50
Checked the issue, I think the problem is on your side. You are logging `payload.data.entries.first` but there may be more entries, so just log entire `payload.data` map.

Adding actionIdentifier to the data map was the easiest way to pass additional information inside RemoteMessage object, the downside is that you will see more data entries than expected.

**Comment by mrdc** [comment] 2021-03-25 13:25
> Checked the issue, I think the problem is on your side. You are logging `payload.data.entries.first` but there may be more entries, so just log entire `payload.data` map.

Double checked - I've looked at wrong output in console, so no issues :)

**Comment by lordgreg** [comment] 2021-04-22 08:54
@moreirawebmaster you can of course re-open the issue if your report wasn't resolved with our update. Thank you.

**Closed** 2021-04-22 08:54 UTC
