### ISSUE TITLE
onMessage does not get called on iOS

### ISSUE THREAD

**Issue by cemozerr** [mwaylabs/flutter-apns#40] opened 2020-12-30 16:19 UTC
onMessage does not get called on iOS. 

I've got notifications set up correctly and working. I'm using onResume and onLaunch well to open up a specific route in my application, yet, I just want to print something or add the data I receive on onMessage, and nothing happens.

**Comment by aytunch** [comment] 2021-01-15 23:22
@cemozerr Have you found a solution? If not, have you tried this fork?:
https://github.com/FirebaseExtended/flutterfire/discussions/4023#discussioncomment-284501

**Comment by szotp** [comment] 2021-03-18 08:34
Hi have you seen [Troubleshooting section](https://github.com/mwaylabs/flutter-apns#troubleshooting)?

Perhaps you managed to fix it, as I just merged your https://github.com/mwaylabs/flutter-apns/pull/41
What was the issue then? I'll add it to FAQ.

**Comment by intoxicated** [comment] 2021-04-16 19:50
I'm facing same issue that `onMessage` does not get called when app is on background. I don't know what but `onMessage` get called at some random point when the app is on foreground.. (after get push)

**Comment by lordgreg** [comment] 2021-04-22 09:00
Hi @intoxicated  - Can you please provide more information:
1. flutter_apns version
2. flutter version
3. code where you've registered on onMessage

Thank you.

**Comment by horam-fs** [comment] 2021-08-02 06:48
I have the same problem, and these are the versions:
1. flutter_apns 1.5.1 (also i have faced it in 1.5.0)
2. flutter version 2.2.0
3. code:
`    final PushConnector connector = ApnsPushConnector()
      ..configure(
          onLaunch: _onLaunch,
          onResume: _onResume,
          onMessage: _onMessage,
          onBackgroundMessage: backgroundMessageHandler);

    connector.token.addListener(() async {
      if (_apnToken == null && null != connector.token.value) {
        _apnToken = connector.token.value;
      }
    });

    connector.requestNotificationPermissions();

    if (connector is ApnsPushConnector) {
      /// display notification in foreground.
      connector.shouldPresent = (_) => Future<bool>.value(true);
    }
    ......
    
      Future<void> _onMessage(RemoteMessage message) async {
    // This is called while the app is on foreground.
    logger.log('onMessage: ${message.data}');

    await onMessageHandler(message.data, message.notification);
  }
  ......`

**Comment by horam-fs** [comment] 2021-08-07 19:19
@lordgreg any updates on this?

**Comment by christofkost** [comment] 2022-01-17 12:28
Closing due to not being able to reproduce. Can you double check with the example app? Perhaps certificate setup is not correct.

**Closed by christofkost** 2022-01-17 12:28 UTC
